language: c

compiler:
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq 

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90

script:
    - make test

after_success:
    - gcc -v
    - gcov -v
    - bash <(curl -s https://codecov.io/bash)
