language: c

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8
  - export CC="gcc-4.8"
  - sudo apt-get install tree

script:
  - make test

after_success:
  - pwd
  - tree
  - bash <(curl -s https://codecov.io/bash)
