language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - gcov-4.8

script:
    - make test

after_success:
    - gcc -v
    - gcov -v
    - bash <(curl -s https://codecov.io/bash)
