language: c

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-4.8
    - sudo update-alternatives --set gcc "/usr/bin/gcc-4.8"
    - sudo update-alternatives --set gcov "/usr/bin/gcov-4.8"


script:
    - make test

after_success:
    - gcc -v
    - gcov -v
    - bash <(curl -s https://codecov.io/bash)
